[tool.uv.workspace]
members = [
  "brest-transport-bot",
  "avelbot-ingestion-py"
]

# (optional) force a single shared venv at root
[tool.uv]
managed = true
package = true

[tool.uv.sources]
avelbot-ingestion-py = { workspace = true}